version: '3'

services:
  mongodb:
    container_name: dock-mongodb
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

  3dmdpider:
    image: swyftg/3dmspider:2.0.0
    container_name: dock-3dmspider
    command: ["python3", "RunSpider.py"]
    links:
      - mongodb
    depends_on:
      - mongodb
